services:
  web:
    image: trader-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trader-app
    restart: always
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - PORT=7000
